// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package wq.wl.message;

public final class Message {

    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_codec_Command_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_codec_Command_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_codec_Result_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_codec_Result_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\tapi.proto\022\005codec\"c\n\007Command\022\022\n\ncommand" +
                        "_id\030\001 \002(\004\022(\n\014command_type\030\002 \002(\0162\022.codec." +
                        "CommandType\022\013\n\003key\030\003 \001(\t\022\r\n\005value\030\004 \001(\t\"" +
                        "_\n\006Result\022\022\n\ncommand_id\030\001 \002(\004\022 \n\010res_cod" +
                        "e\030\002 \002(\0162\016.codec.ResCode\022\017\n\007res_msg\030\003 \001(\t" +
                        "\022\016\n\006result\030\004 \001(\t*(\n\013CommandType\022\007\n\003GET\020\000" +
                        "\022\007\n\003SET\020\001\022\007\n\003DEL\020\002*(\n\007ResCode\022\017\n\013RES_SUC" +
                        "CESS\020\000\022\014\n\010RES_FAIL\020\001B\030\n\rwq.wl.messageB\007M" +
                        "essage"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        internal_static_codec_Command_descriptor =
                                getDescriptor().getMessageTypes().get(0);
                        internal_static_codec_Command_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_codec_Command_descriptor,
                                new String[]{"CommandId", "CommandType", "Key", "Value",});
                        internal_static_codec_Result_descriptor =
                                getDescriptor().getMessageTypes().get(1);
                        internal_static_codec_Result_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_codec_Result_descriptor,
                                new String[]{"CommandId", "ResCode", "ResMsg", "Result",});
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
    }

    private Message() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    /**
     * Protobuf enum {@code codec.CommandType}
     */
    public enum CommandType
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>GET = 0;</code>
         */
        GET(0, 0),
        /**
         * <code>SET = 1;</code>
         */
        SET(1, 1),
        /**
         * <code>DEL = 2;</code>
         */
        DEL(2, 2),
        ;

        /**
         * <code>GET = 0;</code>
         */
        public static final int GET_VALUE = 0;

        /**
         * <code>SET = 1;</code>
         */
        public static final int SET_VALUE = 1;

        /**
         * <code>DEL = 2;</code>
         */
        public static final int DEL_VALUE = 2;
        private static final CommandType[] VALUES = values();
        private static com.google.protobuf.Internal.EnumLiteMap<CommandType>
                internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
                    public CommandType findValueByNumber(int number) {
                        return CommandType.valueOf(number);
                    }
                };
        private final int index;
        private final int value;

        private CommandType(int index, int value) {
            this.index = index;
            this.value = value;
        }

        public static CommandType valueOf(int value) {
            switch (value) {
                case 0:
                    return GET;
                case 1:
                    return SET;
                case 2:
                    return DEL;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
        internalGetValueMap() {
            return internalValueMap;
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return wq.wl.message.Message.getDescriptor().getEnumTypes().get(0);
        }

        public static CommandType valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            return VALUES[desc.getIndex()];
        }

        public final int getNumber() {
            return value;
        }

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            return getDescriptor().getValues().get(index);
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        // @@protoc_insertion_point(enum_scope:codec.CommandType)
    }

    /**
     * Protobuf enum {@code codec.ResCode}
     */
    public enum ResCode
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>RES_SUCCESS = 0;</code>
         */
        RES_SUCCESS(0, 0),
        /**
         * <code>RES_FAIL = 1;</code>
         */
        RES_FAIL(1, 1),
        ;

        /**
         * <code>RES_SUCCESS = 0;</code>
         */
        public static final int RES_SUCCESS_VALUE = 0;

        /**
         * <code>RES_FAIL = 1;</code>
         */
        public static final int RES_FAIL_VALUE = 1;
        private static final ResCode[] VALUES = values();
        private static com.google.protobuf.Internal.EnumLiteMap<ResCode>
                internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<ResCode>() {
                    public ResCode findValueByNumber(int number) {
                        return ResCode.valueOf(number);
                    }
                };
        private final int index;
        private final int value;

        private ResCode(int index, int value) {
            this.index = index;
            this.value = value;
        }

        public static ResCode valueOf(int value) {
            switch (value) {
                case 0:
                    return RES_SUCCESS;
                case 1:
                    return RES_FAIL;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<ResCode>
        internalGetValueMap() {
            return internalValueMap;
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return wq.wl.message.Message.getDescriptor().getEnumTypes().get(1);
        }

        public static ResCode valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            return VALUES[desc.getIndex()];
        }

        public final int getNumber() {
            return value;
        }

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            return getDescriptor().getValues().get(index);
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        // @@protoc_insertion_point(enum_scope:codec.ResCode)
    }

    public interface CommandOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // required uint64 command_id = 1;

        /**
         * <code>required uint64 command_id = 1;</code>
         *
         * <pre>
         * 请求id
         * </pre>
         */
        boolean hasCommandId();

        /**
         * <code>required .codec.CommandType command_type = 2;</code>
         */
        boolean hasCommandType();

        // required .codec.CommandType command_type = 2;

        /**
         * <code>optional string key = 3;</code>
         */
        boolean hasKey();

        /**
         * <code>optional string value = 4;</code>
         */
        boolean hasValue();

        // optional string key = 3;

        /**
         * <code>required uint64 command_id = 1;</code>
         *
         * <pre>
         * 请求id
         * </pre>
         */
        long getCommandId();

        /**
         * <code>required .codec.CommandType command_type = 2;</code>
         */
        wq.wl.message.Message.CommandType getCommandType();

        /**
         * <code>optional string key = 3;</code>
         */
        String getKey();

        // optional string value = 4;

        /**
         * <code>optional string key = 3;</code>
         */
        com.google.protobuf.ByteString
        getKeyBytes();

        /**
         * <code>optional string value = 4;</code>
         */
        String getValue();

        /**
         * <code>optional string value = 4;</code>
         */
        com.google.protobuf.ByteString
        getValueBytes();
    }

    public interface ResultOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // required uint64 command_id = 1;

        /**
         * <code>required uint64 command_id = 1;</code>
         *
         * <pre>
         * 请求id
         * </pre>
         */
        boolean hasCommandId();

        /**
         * <code>required .codec.ResCode res_code = 2;</code>
         *
         * <pre>
         * 返回码，0：成功，1：失败
         * </pre>
         */
        boolean hasResCode();

        // required .codec.ResCode res_code = 2;

        /**
         * <code>optional string res_msg = 3;</code>
         *
         * <pre>
         * 返回失败时的错误消息
         * </pre>
         */
        boolean hasResMsg();

        /**
         * <code>optional string result = 4;</code>
         */
        boolean hasResult();

        // optional string res_msg = 3;

        /**
         * <code>required uint64 command_id = 1;</code>
         *
         * <pre>
         * 请求id
         * </pre>
         */
        long getCommandId();

        /**
         * <code>required .codec.ResCode res_code = 2;</code>
         *
         * <pre>
         * 返回码，0：成功，1：失败
         * </pre>
         */
        wq.wl.message.Message.ResCode getResCode();

        /**
         * <code>optional string res_msg = 3;</code>
         *
         * <pre>
         * 返回失败时的错误消息
         * </pre>
         */
        String getResMsg();

        // optional string result = 4;

        /**
         * <code>optional string res_msg = 3;</code>
         *
         * <pre>
         * 返回失败时的错误消息
         * </pre>
         */
        com.google.protobuf.ByteString
        getResMsgBytes();

        /**
         * <code>optional string result = 4;</code>
         */
        String getResult();

        /**
         * <code>optional string result = 4;</code>
         */
        com.google.protobuf.ByteString
        getResultBytes();
    }

    /**
     * Protobuf type {@code codec.Command}
     */
    public static final class Command extends
            com.google.protobuf.GeneratedMessage
            implements CommandOrBuilder {

        // required uint64 command_id = 1;
        public static final int COMMAND_ID_FIELD_NUMBER = 1;
        // required .codec.CommandType command_type = 2;
        public static final int COMMAND_TYPE_FIELD_NUMBER = 2;
        // optional string key = 3;
        public static final int KEY_FIELD_NUMBER = 3;
        // optional string value = 4;
        public static final int VALUE_FIELD_NUMBER = 4;
        private static final long serialVersionUID = 0L;
        private static final Command defaultInstance;
        public static com.google.protobuf.Parser<Command> PARSER =
                new com.google.protobuf.AbstractParser<Command>() {
                    public Command parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new Command(input, extensionRegistry);
                    }
                };

        static {
            defaultInstance = new Command(true);
            defaultInstance.initFields();
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;
        private int bitField0_;
        private long commandId_;
        private wq.wl.message.Message.CommandType commandType_;
        private Object key_;
        private Object value_;
        private byte memoizedIsInitialized = -1;
        private int memoizedSerializedSize = -1;

        // Use Command.newBuilder() to construct.
        private Command(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private Command(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private Command(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            commandId_ = input.readUInt64();
                            break;
                        }
                        case 16: {
                            int rawValue = input.readEnum();
                            wq.wl.message.Message.CommandType value = wq.wl.message.Message.CommandType.valueOf(rawValue);
                            if (value == null) {
                                unknownFields.mergeVarintField(2, rawValue);
                            } else {
                                bitField0_ |= 0x00000002;
                                commandType_ = value;
                            }
                            break;
                        }
                        case 26: {
                            bitField0_ |= 0x00000004;
                            key_ = input.readBytes();
                            break;
                        }
                        case 34: {
                            bitField0_ |= 0x00000008;
                            value_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static Command getDefaultInstance() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return wq.wl.message.Message.internal_static_codec_Command_descriptor;
        }

        public static wq.wl.message.Message.Command parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static wq.wl.message.Message.Command parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static wq.wl.message.Message.Command parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static wq.wl.message.Message.Command parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static wq.wl.message.Message.Command parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static wq.wl.message.Message.Command parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static wq.wl.message.Message.Command parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static wq.wl.message.Message.Command parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static wq.wl.message.Message.Command parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static wq.wl.message.Message.Command parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public static Builder newBuilder(wq.wl.message.Message.Command prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        /**
         * <code>required uint64 command_id = 1;</code>
         *
         * <pre>
         * 请求id
         * </pre>
         */
        public boolean hasCommandId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required .codec.CommandType command_type = 2;</code>
         */
        public boolean hasCommandType() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional string key = 3;</code>
         */
        public boolean hasKey() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>optional string value = 4;</code>
         */
        public boolean hasValue() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeUInt64(1, commandId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeEnum(2, commandType_.getNumber());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBytes(3, getKeyBytes());
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeBytes(4, getValueBytes());
            }
            getUnknownFields().writeTo(output);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return wq.wl.message.Message.internal_static_codec_Command_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            wq.wl.message.Message.Command.class, wq.wl.message.Message.Command.Builder.class);
        }

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        private void initFields() {
            commandId_ = 0L;
            commandType_ = wq.wl.message.Message.CommandType.GET;
            key_ = "";
            value_ = "";
        }

        public Command getDefaultInstanceForType() {
            return defaultInstance;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @Override
        public com.google.protobuf.Parser<Command> getParserForType() {
            return PARSER;
        }

        /**
         * <code>required uint64 command_id = 1;</code>
         *
         * <pre>
         * 请求id
         * </pre>
         */
        public long getCommandId() {
            return commandId_;
        }

        /**
         * <code>required .codec.CommandType command_type = 2;</code>
         */
        public wq.wl.message.Message.CommandType getCommandType() {
            return commandType_;
        }

        /**
         * <code>optional string key = 3;</code>
         */
        public String getKey() {
            Object ref = key_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    key_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string key = 3;</code>
         */
        public com.google.protobuf.ByteString
        getKeyBytes() {
            Object ref = key_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                key_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional string value = 4;</code>
         */
        public String getValue() {
            Object ref = value_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    value_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string value = 4;</code>
         */
        public com.google.protobuf.ByteString
        getValueBytes() {
            Object ref = value_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                value_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            if (!hasCommandId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasCommandType()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(1, commandId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(2, commandType_.getNumber());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, getKeyBytes());
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(4, getValueBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        /**
         * Protobuf type {@code codec.Command}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements wq.wl.message.Message.CommandOrBuilder {

            private int bitField0_;
            // required uint64 command_id = 1;
            private long commandId_;
            // required .codec.CommandType command_type = 2;
            private wq.wl.message.Message.CommandType commandType_ = wq.wl.message.Message.CommandType.GET;
            // optional string key = 3;
            private Object key_ = "";
            // optional string value = 4;
            private Object value_ = "";

            // Construct using wq.wl.message.Message.Command.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return wq.wl.message.Message.internal_static_codec_Command_descriptor;
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                commandId_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000001);
                commandType_ = wq.wl.message.Message.CommandType.GET;
                bitField0_ = (bitField0_ & ~0x00000002);
                key_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                value_ = "";
                bitField0_ = (bitField0_ & ~0x00000008);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public wq.wl.message.Message.Command build() {
                wq.wl.message.Message.Command result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public wq.wl.message.Message.Command buildPartial() {
                wq.wl.message.Message.Command result = new wq.wl.message.Message.Command(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.commandId_ = commandId_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.commandType_ = commandType_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.key_ = key_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.value_ = value_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof wq.wl.message.Message.Command) {
                    return mergeFrom((wq.wl.message.Message.Command) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(wq.wl.message.Message.Command other) {
                if (other == wq.wl.message.Message.Command.getDefaultInstance()) return this;
                if (other.hasCommandId()) {
                    setCommandId(other.getCommandId());
                }
                if (other.hasCommandType()) {
                    setCommandType(other.getCommandType());
                }
                if (other.hasKey()) {
                    bitField0_ |= 0x00000004;
                    key_ = other.key_;
                    onChanged();
                }
                if (other.hasValue()) {
                    bitField0_ |= 0x00000008;
                    value_ = other.value_;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                wq.wl.message.Message.Command parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (wq.wl.message.Message.Command) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>required uint64 command_id = 1;</code>
             *
             * <pre>
             * 请求id
             * </pre>
             */
            public boolean hasCommandId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required uint64 command_id = 1;</code>
             *
             * <pre>
             * 请求id
             * </pre>
             */
            public Builder clearCommandId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                commandId_ = 0L;
                onChanged();
                return this;
            }

            /**
             * <code>required .codec.CommandType command_type = 2;</code>
             */
            public boolean hasCommandType() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required .codec.CommandType command_type = 2;</code>
             */
            public Builder clearCommandType() {
                bitField0_ = (bitField0_ & ~0x00000002);
                commandType_ = wq.wl.message.Message.CommandType.GET;
                onChanged();
                return this;
            }

            /**
             * <code>optional string key = 3;</code>
             */
            public boolean hasKey() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>optional string key = 3;</code>
             */
            public Builder clearKey() {
                bitField0_ = (bitField0_ & ~0x00000004);
                key_ = getDefaultInstance().getKey();
                onChanged();
                return this;
            }

            /**
             * <code>optional string value = 4;</code>
             */
            public boolean hasValue() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            /**
             * <code>optional string value = 4;</code>
             */
            public Builder clearValue() {
                bitField0_ = (bitField0_ & ~0x00000008);
                value_ = getDefaultInstance().getValue();
                onChanged();
                return this;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return wq.wl.message.Message.internal_static_codec_Command_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                wq.wl.message.Message.Command.class, wq.wl.message.Message.Command.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return wq.wl.message.Message.internal_static_codec_Command_descriptor;
            }

            public wq.wl.message.Message.Command getDefaultInstanceForType() {
                return wq.wl.message.Message.Command.getDefaultInstance();
            }

            public final boolean isInitialized() {
                if (!hasCommandId()) {

                    return false;
                }
                if (!hasCommandType()) {

                    return false;
                }
                return true;
            }

            /**
             * <code>required uint64 command_id = 1;</code>
             *
             * <pre>
             * 请求id
             * </pre>
             */
            public long getCommandId() {
                return commandId_;
            }

            /**
             * <code>required uint64 command_id = 1;</code>
             *
             * <pre>
             * 请求id
             * </pre>
             */
            public Builder setCommandId(long value) {
                bitField0_ |= 0x00000001;
                commandId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required .codec.CommandType command_type = 2;</code>
             */
            public wq.wl.message.Message.CommandType getCommandType() {
                return commandType_;
            }

            /**
             * <code>required .codec.CommandType command_type = 2;</code>
             */
            public Builder setCommandType(wq.wl.message.Message.CommandType value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                commandType_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string key = 3;</code>
             */
            public String getKey() {
                Object ref = key_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    key_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string key = 3;</code>
             */
            public Builder setKey(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                key_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string key = 3;</code>
             */
            public com.google.protobuf.ByteString
            getKeyBytes() {
                Object ref = key_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    key_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string key = 3;</code>
             */
            public Builder setKeyBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                key_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string value = 4;</code>
             */
            public String getValue() {
                Object ref = value_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    value_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string value = 4;</code>
             */
            public Builder setValue(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                value_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string value = 4;</code>
             */
            public com.google.protobuf.ByteString
            getValueBytes() {
                Object ref = value_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    value_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string value = 4;</code>
             */
            public Builder setValueBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                value_ = value;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:codec.Command)
        }

        // @@protoc_insertion_point(class_scope:codec.Command)
    }

    /**
     * Protobuf type {@code codec.Result}
     */
    public static final class Result extends
            com.google.protobuf.GeneratedMessage
            implements ResultOrBuilder {

        // required uint64 command_id = 1;
        public static final int COMMAND_ID_FIELD_NUMBER = 1;
        // required .codec.ResCode res_code = 2;
        public static final int RES_CODE_FIELD_NUMBER = 2;
        // optional string res_msg = 3;
        public static final int RES_MSG_FIELD_NUMBER = 3;
        // optional string result = 4;
        public static final int RESULT_FIELD_NUMBER = 4;
        private static final long serialVersionUID = 0L;
        private static final Result defaultInstance;
        public static com.google.protobuf.Parser<Result> PARSER =
                new com.google.protobuf.AbstractParser<Result>() {
                    public Result parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new Result(input, extensionRegistry);
                    }
                };

        static {
            defaultInstance = new Result(true);
            defaultInstance.initFields();
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;
        private int bitField0_;
        private long commandId_;
        private wq.wl.message.Message.ResCode resCode_;
        private Object resMsg_;
        private Object result_;
        private byte memoizedIsInitialized = -1;
        private int memoizedSerializedSize = -1;

        // Use Result.newBuilder() to construct.
        private Result(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private Result(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private Result(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            commandId_ = input.readUInt64();
                            break;
                        }
                        case 16: {
                            int rawValue = input.readEnum();
                            wq.wl.message.Message.ResCode value = wq.wl.message.Message.ResCode.valueOf(rawValue);
                            if (value == null) {
                                unknownFields.mergeVarintField(2, rawValue);
                            } else {
                                bitField0_ |= 0x00000002;
                                resCode_ = value;
                            }
                            break;
                        }
                        case 26: {
                            bitField0_ |= 0x00000004;
                            resMsg_ = input.readBytes();
                            break;
                        }
                        case 34: {
                            bitField0_ |= 0x00000008;
                            result_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static Result getDefaultInstance() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return wq.wl.message.Message.internal_static_codec_Result_descriptor;
        }

        public static wq.wl.message.Message.Result parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static wq.wl.message.Message.Result parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static wq.wl.message.Message.Result parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static wq.wl.message.Message.Result parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static wq.wl.message.Message.Result parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static wq.wl.message.Message.Result parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static wq.wl.message.Message.Result parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static wq.wl.message.Message.Result parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static wq.wl.message.Message.Result parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static wq.wl.message.Message.Result parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public static Builder newBuilder(wq.wl.message.Message.Result prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        /**
         * <code>required uint64 command_id = 1;</code>
         *
         * <pre>
         * 请求id
         * </pre>
         */
        public boolean hasCommandId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required .codec.ResCode res_code = 2;</code>
         *
         * <pre>
         * 返回码，0：成功，1：失败
         * </pre>
         */
        public boolean hasResCode() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional string res_msg = 3;</code>
         *
         * <pre>
         * 返回失败时的错误消息
         * </pre>
         */
        public boolean hasResMsg() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>optional string result = 4;</code>
         */
        public boolean hasResult() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeUInt64(1, commandId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeEnum(2, resCode_.getNumber());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBytes(3, getResMsgBytes());
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeBytes(4, getResultBytes());
            }
            getUnknownFields().writeTo(output);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return wq.wl.message.Message.internal_static_codec_Result_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            wq.wl.message.Message.Result.class, wq.wl.message.Message.Result.Builder.class);
        }

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        private void initFields() {
            commandId_ = 0L;
            resCode_ = wq.wl.message.Message.ResCode.RES_SUCCESS;
            resMsg_ = "";
            result_ = "";
        }

        public Result getDefaultInstanceForType() {
            return defaultInstance;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @Override
        public com.google.protobuf.Parser<Result> getParserForType() {
            return PARSER;
        }

        /**
         * <code>required uint64 command_id = 1;</code>
         *
         * <pre>
         * 请求id
         * </pre>
         */
        public long getCommandId() {
            return commandId_;
        }

        /**
         * <code>required .codec.ResCode res_code = 2;</code>
         *
         * <pre>
         * 返回码，0：成功，1：失败
         * </pre>
         */
        public wq.wl.message.Message.ResCode getResCode() {
            return resCode_;
        }

        /**
         * <code>optional string res_msg = 3;</code>
         *
         * <pre>
         * 返回失败时的错误消息
         * </pre>
         */
        public String getResMsg() {
            Object ref = resMsg_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    resMsg_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string res_msg = 3;</code>
         *
         * <pre>
         * 返回失败时的错误消息
         * </pre>
         */
        public com.google.protobuf.ByteString
        getResMsgBytes() {
            Object ref = resMsg_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                resMsg_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional string result = 4;</code>
         */
        public String getResult() {
            Object ref = result_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    result_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string result = 4;</code>
         */
        public com.google.protobuf.ByteString
        getResultBytes() {
            Object ref = result_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                result_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            if (!hasCommandId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasResCode()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(1, commandId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(2, resCode_.getNumber());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, getResMsgBytes());
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(4, getResultBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        /**
         * Protobuf type {@code codec.Result}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements wq.wl.message.Message.ResultOrBuilder {

            private int bitField0_;
            // required uint64 command_id = 1;
            private long commandId_;
            // required .codec.ResCode res_code = 2;
            private wq.wl.message.Message.ResCode resCode_ = wq.wl.message.Message.ResCode.RES_SUCCESS;
            // optional string res_msg = 3;
            private Object resMsg_ = "";
            // optional string result = 4;
            private Object result_ = "";

            // Construct using wq.wl.message.Message.Result.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return wq.wl.message.Message.internal_static_codec_Result_descriptor;
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                commandId_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000001);
                resCode_ = wq.wl.message.Message.ResCode.RES_SUCCESS;
                bitField0_ = (bitField0_ & ~0x00000002);
                resMsg_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                result_ = "";
                bitField0_ = (bitField0_ & ~0x00000008);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public wq.wl.message.Message.Result build() {
                wq.wl.message.Message.Result result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public wq.wl.message.Message.Result buildPartial() {
                wq.wl.message.Message.Result result = new wq.wl.message.Message.Result(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.commandId_ = commandId_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.resCode_ = resCode_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.resMsg_ = resMsg_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.result_ = result_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof wq.wl.message.Message.Result) {
                    return mergeFrom((wq.wl.message.Message.Result) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(wq.wl.message.Message.Result other) {
                if (other == wq.wl.message.Message.Result.getDefaultInstance()) return this;
                if (other.hasCommandId()) {
                    setCommandId(other.getCommandId());
                }
                if (other.hasResCode()) {
                    setResCode(other.getResCode());
                }
                if (other.hasResMsg()) {
                    bitField0_ |= 0x00000004;
                    resMsg_ = other.resMsg_;
                    onChanged();
                }
                if (other.hasResult()) {
                    bitField0_ |= 0x00000008;
                    result_ = other.result_;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                wq.wl.message.Message.Result parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (wq.wl.message.Message.Result) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>required uint64 command_id = 1;</code>
             *
             * <pre>
             * 请求id
             * </pre>
             */
            public boolean hasCommandId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required uint64 command_id = 1;</code>
             *
             * <pre>
             * 请求id
             * </pre>
             */
            public Builder clearCommandId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                commandId_ = 0L;
                onChanged();
                return this;
            }

            /**
             * <code>required .codec.ResCode res_code = 2;</code>
             *
             * <pre>
             * 返回码，0：成功，1：失败
             * </pre>
             */
            public boolean hasResCode() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required .codec.ResCode res_code = 2;</code>
             *
             * <pre>
             * 返回码，0：成功，1：失败
             * </pre>
             */
            public Builder clearResCode() {
                bitField0_ = (bitField0_ & ~0x00000002);
                resCode_ = wq.wl.message.Message.ResCode.RES_SUCCESS;
                onChanged();
                return this;
            }

            /**
             * <code>optional string res_msg = 3;</code>
             *
             * <pre>
             * 返回失败时的错误消息
             * </pre>
             */
            public boolean hasResMsg() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>optional string res_msg = 3;</code>
             *
             * <pre>
             * 返回失败时的错误消息
             * </pre>
             */
            public Builder clearResMsg() {
                bitField0_ = (bitField0_ & ~0x00000004);
                resMsg_ = getDefaultInstance().getResMsg();
                onChanged();
                return this;
            }

            /**
             * <code>optional string result = 4;</code>
             */
            public boolean hasResult() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            /**
             * <code>optional string result = 4;</code>
             */
            public Builder clearResult() {
                bitField0_ = (bitField0_ & ~0x00000008);
                result_ = getDefaultInstance().getResult();
                onChanged();
                return this;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return wq.wl.message.Message.internal_static_codec_Result_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                wq.wl.message.Message.Result.class, wq.wl.message.Message.Result.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return wq.wl.message.Message.internal_static_codec_Result_descriptor;
            }

            public wq.wl.message.Message.Result getDefaultInstanceForType() {
                return wq.wl.message.Message.Result.getDefaultInstance();
            }

            public final boolean isInitialized() {
                if (!hasCommandId()) {

                    return false;
                }
                if (!hasResCode()) {

                    return false;
                }
                return true;
            }

            /**
             * <code>required uint64 command_id = 1;</code>
             *
             * <pre>
             * 请求id
             * </pre>
             */
            public long getCommandId() {
                return commandId_;
            }

            /**
             * <code>required uint64 command_id = 1;</code>
             *
             * <pre>
             * 请求id
             * </pre>
             */
            public Builder setCommandId(long value) {
                bitField0_ |= 0x00000001;
                commandId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required .codec.ResCode res_code = 2;</code>
             *
             * <pre>
             * 返回码，0：成功，1：失败
             * </pre>
             */
            public wq.wl.message.Message.ResCode getResCode() {
                return resCode_;
            }

            /**
             * <code>required .codec.ResCode res_code = 2;</code>
             *
             * <pre>
             * 返回码，0：成功，1：失败
             * </pre>
             */
            public Builder setResCode(wq.wl.message.Message.ResCode value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                resCode_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string res_msg = 3;</code>
             *
             * <pre>
             * 返回失败时的错误消息
             * </pre>
             */
            public String getResMsg() {
                Object ref = resMsg_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    resMsg_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string res_msg = 3;</code>
             *
             * <pre>
             * 返回失败时的错误消息
             * </pre>
             */
            public Builder setResMsg(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                resMsg_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string res_msg = 3;</code>
             *
             * <pre>
             * 返回失败时的错误消息
             * </pre>
             */
            public com.google.protobuf.ByteString
            getResMsgBytes() {
                Object ref = resMsg_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    resMsg_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string res_msg = 3;</code>
             *
             * <pre>
             * 返回失败时的错误消息
             * </pre>
             */
            public Builder setResMsgBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                resMsg_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string result = 4;</code>
             */
            public String getResult() {
                Object ref = result_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    result_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string result = 4;</code>
             */
            public Builder setResult(
                    String value) {
                //     if (value == null) {
                // throw new NullPointerException();
                // }
                bitField0_ |= 0x00000008;
                result_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string result = 4;</code>
             */
            public com.google.protobuf.ByteString
            getResultBytes() {
                Object ref = result_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    result_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string result = 4;</code>
             */
            public Builder setResultBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                result_ = value;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:codec.Result)
        }

        // @@protoc_insertion_point(class_scope:codec.Result)
    }

    // @@protoc_insertion_point(outer_class_scope)
}
